spring.application.name=backend
# 1. Adres bazy danych i dane logowania
spring.datasource.url=jdbc:postgresql://localhost:5432/kino
spring.datasource.username=postgres
spring.datasource.password=4127

# 2. Ustawienia Hibernate (magia, która tworzy tabele)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Dodatki do nauki
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jakbedn86@gmail.com
spring.mail.password=lggd flze tblf fhtf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true